openapi: 3.0.3
info:
  title: NFC Pay AutoWrite API
  version: 1.0.0
servers:
  - url: https://your-app.vercel.app
paths:
  /api/v1/bootstrap:
    get:
      summary: Bootstrap device (register/upsert by key)
      parameters:
        - in: header
          name: x-device-key
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /api/v1/payments/generate:
    post:
      summary: Create payment and optionally queue tag write job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount: { type: number }
                currency: { type: string }
                label: { type: string }
                autoWrite: { type: boolean }
      responses:
        '200': { description: OK }
  /api/v1/device/next:
    get:
      summary: Device polls for next queued job
      parameters:
        - in: header
          name: x-device-key
          required: true
          schema: { type: string }
      responses:
        '200': { description: Job returned }
        '204': { description: No job }
  /api/v1/device/ack:
    post:
      summary: Device acknowledges job result
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                jobId: { type: string }
                ok: { type: boolean }
      responses:
        '200': { description: OK }
